# Generated by Django 6.0.2 on 2026-02-28 10:05

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_foot_ball_league_id', models.IntegerField()),
                ('divison', models.CharField()),
                ('league_logo', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('record', models.TextField(max_length=200)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('round', models.IntegerField()),
                ('match_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture_image', models.BinaryField()),
                ('record_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jfootball_record.matchrecords')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_foot_ball_team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=15, unique=True)),
                ('team_logo', models.CharField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jfootball_record.leagues')),
            ],
        ),
        migrations.AddField(
            model_name='matchrecords',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='jfootball_record.teams'),
        ),
        migrations.AddField(
            model_name='matchrecords',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='jfootball_record.teams'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.IntegerField(choices=[(1, 'Man'), (2, 'Woman')])),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='jfootball_record_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Nice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jfootball_record.matchrecords')),
                ('post_by', models.ForeignKey(db_column='post_by', on_delete=django.db.models.deletion.CASCADE, to='jfootball_record.users')),
            ],
        ),
        migrations.AddField(
            model_name='matchrecords',
            name='created_by',
            field=models.ForeignKey(db_column='comment_by', on_delete=django.db.models.deletion.CASCADE, to='jfootball_record.users'),
        ),
        migrations.CreateModel(
            name='FavoriteTeams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jfootball_record.teams', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jfootball_record.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=50)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jfootball_record.matchrecords')),
                ('comment_by', models.ForeignKey(db_column='comment_by', on_delete=django.db.models.deletion.CASCADE, to='jfootball_record.users')),
            ],
        ),
    ]
