# Generated by Django 6.0.2 on 2026-03-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfootball_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_by',
            field=models.ForeignKey(db_column='comment_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jfootball_record.users'),
        ),
        migrations.AlterField(
            model_name='matchrecords',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away', to='jfootball_record.teams'),
        ),
        migrations.AlterField(
            model_name='matchrecords',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home', to='jfootball_record.teams'),
        ),
    ]
