# Generated by Django 6.0.2 on 2026-03-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfootball_record', '0002_alter_comments_comment_by_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nice',
            constraint=models.UniqueConstraint(fields=('record', 'post_by'), name='unique_nice'),
        ),
    ]
